name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to the gh-pages branch
      - uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'ryanyen2/ryanyen2.github.io'
          branch: 'master'     # Default branch is gh-pages
          jekyll_src: './'       # Default is the current directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''     # Use empty if deploying to custom domain or root path
          bundler_ver: '>=0'     # Default is latest bundler version
          cname: ''              # Default is no CNAME 